# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Sep 22 15:39:21 2023
# ------------------------------------------------

package:
  name: jsonpointer
  version: '2.4'
source:
  sha256: 585cee82b70211fa9e6043b7bb89db6e1aa49524340dde8ad6b63206ea689d88
  url: https://pypi.io/packages/source/j/jsonpointer/jsonpointer-2.4.tar.gz
build:
  number: '3'
  script: /home/conda/feedstock_root/build_artifacts/jsonpointer_1695397259263/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . -vv
  string: py39h4162558_3
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - expat 2.5.0 hcb278e6_1
    - gdbm 1.18 h0a1914f_2
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libsqlite 3.43.0 h2797004_0
    - libxcb 1.15 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.3 hd590300_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pthread-stubs 0.4 h36c2ea0_1001
    - pypy3.9 7.3.12 h9557127_4
    - python 3.9.17 0_73_pypy
    - python_abi 3.9 4_pypy39_pp73
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - sqlite 3.43.0 h2c6b66d_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xorg-kbproto 1.0.7 h7f98852_1002
    - xorg-libx11 1.8.6 h8ee46fc_0
    - xorg-libxau 1.0.11 hd590300_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-xextproto 7.3.0 h0b41bf4_1003
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
  run:
    - pypy3.9 >=7.3.12
    - python >=3.9,<3.10.0a0
    - python_abi 3.9 *_pypy39_pp73
test:
  commands:
    - pip check
  imports:
    - jsonpointer
  requires:
    - pip
about:
  home: https://github.com/stefankoegl/python-json-pointer
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Identify specific nodes in a JSON document (RFC 6901)
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - anguslees
    - xhochy
