# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jan 26 09:53:59 2023
# ------------------------------------------------

package:
  name: lz4-c
  version: 1.9.4
source:
  sha256: 0b0e3aa07c8c063ddf40b082bdf7e37a1562bda40a0ff5272957f3e987e0e54b
  url: https://github.com/lz4/lz4/archive/v1.9.4.tar.gz
build:
  number: '0'
  run_exports:
    - lz4-c >=1.9.4,<1.10.0a0
  string: hcb278e6_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.39 he00db2b_1
    - binutils_linux-64 2.39 h5fc0e48_11
    - gcc_impl_linux-64 11.3.0 hab1b70f_19
    - gcc_linux-64 11.3.0 he6f903b_11
    - gxx_impl_linux-64 11.3.0 hab1b70f_19
    - gxx_linux-64 11.3.0 hc203a17_11
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libgcc-devel_linux-64 11.3.0 h210ce93_19
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libsanitizer 11.3.0 h239ccf8_19
    - libstdcxx-devel_linux-64 11.3.0 h210ce93_19
    - libstdcxx-ng 12.2.0 h46fd767_19
    - make 4.3 hd18ef5c_1
    - patch 2.7.6 h7f98852_1002
    - sysroot_linux-64 2.12 he073ed8_15
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libstdcxx-ng 12.2.0 h46fd767_19
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
about:
  description: 'LZ4 is lossless compression algorithm, providing compression speed
    at 400

    MB/s per core (0.16 Bytes/cycle). It features an extremely fast decoder,

    with speed in multiple GB/s per core (0.71 Bytes/cycle). A high compression

    derivative, called LZ4_HC, is available, trading customizable CPU time for

    compression ratio. LZ4 library is provided as open source software using a

    BSD license.

    '
  home: https://www.lz4.org
  license: BSD-2-Clause
  license_file: lib/LICENSE
  summary: Extremely Fast Compression algorithm
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mingwandroid
    - rmax
    - wesm
    - xhochy
