# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Feb  7 09:27:09 2024
# ------------------------------------------------

package:
  name: ruamel.yaml
  version: 0.18.6
source:
  sha256: 8b27e6a217e786c6fbe5634d8f3f11bc63e0f80f6a5890f28863d9c45aac311b
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-0.18.6.tar.gz
build:
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/ruamel.yaml_1707298109947/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps -vv
  script_env:
    - RUAMEL_NO_LONG_DESCRIPTION=1
  string: py39hf860d4a_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_5
    - gcc_linux-64 12.3.0 h76fc315_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libsanitizer 12.3.0 h0f45ef3_5
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - expat 2.5.0 hcb278e6_1
    - gdbm 1.18 h0a1914f_2
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libsqlite 3.44.2 h2797004_0
    - libxcb 1.15 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - pip 24.0 pyhd8ed1ab_0
    - pthread-stubs 0.4 h36c2ea0_1001
    - pypy3.9 7.3.15 h9557127_0
    - python 3.9.18 1_73_pypy
    - python_abi 3.9 4_pypy39_pp73
    - readline 8.2 h8228510_1
    - ruamel 1.0 py39h4162558_8
    - setuptools 69.0.3 pyhd8ed1ab_0
    - sqlite 3.44.2 h2c6b66d_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xorg-kbproto 1.0.7 h7f98852_1002
    - xorg-libx11 1.8.7 h8ee46fc_0
    - xorg-libxau 1.0.11 hd590300_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-xextproto 7.3.0 h0b41bf4_1003
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
  run:
    - libgcc-ng >=12
    - pypy3.9 >=7.3.15
    - python >=3.9,<3.10.0a0
    - python_abi 3.9 *_pypy39_pp73
    - ruamel.yaml.clib >=0.1.2
test:
  imports:
    - ruamel.yaml
about:
  home: https://sourceforge.net/p/ruamel-yaml
  license: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML
    3.11 which supports YAML1.1
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240207.4.1
  recipe-maintainers:
    - davidbrochart
    - jakirkham
    - mbargull
    - mwcraig
    - ocefpaf
    - pelson
    - xhochy
  remote_url: https://github.com/conda-forge/ruamel.yaml-feedstock
  sha: 03740c4037744f3c708e6a26ec396d5b47d36744
