# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Feb 26 17:44:42 2024
# ------------------------------------------------

package:
  name: archspec
  version: 0.2.3
source:
  sha256: d07deb5b6e2ab3b74861e217523d02e69be8522f6e6565f4cc5d2062eb1a5d2c
  url: https://pypi.io/packages/source/a/archspec/archspec-0.2.3.tar.gz
build:
  entry_points:
    - archspec = archspec.cli:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/archspec_1708969572489/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - brotli-python 1.1.0 py312h30efb56_1
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - cachecontrol 0.14.0 pyhd8ed1ab_0
    - cachecontrol-with-filecache 0.14.0 pyhd8ed1ab_0
    - certifi 2024.2.2 pyhd8ed1ab_0
    - cffi 1.16.0 py312hf06ca03_0
    - charset-normalizer 3.3.2 pyhd8ed1ab_0
    - cleo 2.1.0 pyhd8ed1ab_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - crashtest 0.4.1 pyhd8ed1ab_0
    - cryptography 42.0.5 py312h241aef2_0
    - dbus 1.13.6 h5008d03_3
    - distlib 0.3.8 pyhd8ed1ab_0
    - dulwich 0.21.7 py312h98912ed_0
    - expat 2.5.0 hcb278e6_1
    - filelock 3.13.1 pyhd8ed1ab_0
    - gettext 0.21.1 h27087fc_0
    - idna 3.6 pyhd8ed1ab_0
    - importlib-metadata 7.0.1 pyha770c72_0
    - jaraco.classes 3.3.1 pyhd8ed1ab_0
    - jeepney 0.8.0 pyhd8ed1ab_0
    - keyring 24.3.0 py312h7900ff3_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libblas 3.9.0 21_linux64_openblas
    - libcblas 3.9.0 21_linux64_openblas
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgfortran-ng 13.2.0 h69a702a_5
    - libgfortran5 13.2.0 ha4646dd_5
    - libglib 2.78.4 h783c2da_0
    - libgomp 13.2.0 h807b86a_5
    - libiconv 1.17 hd590300_2
    - liblapack 3.9.0 21_linux64_openblas
    - libnsl 2.0.1 hd590300_0
    - libopenblas 0.3.26 pthreads_h413a1c8_0
    - libsqlite 3.45.1 h2797004_0
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - more-itertools 10.2.0 pyhd8ed1ab_0
    - msgpack-python 1.0.7 py312h8572e83_0
    - ncurses 6.4 h59595ed_2
    - numpy 1.26.4 py312heda63a1_0
    - openssl 3.2.1 hd590300_0
    - packaging 23.2 pyhd8ed1ab_0
    - pcre2 10.42 hcad00b1_0
    - pexpect 4.9.0 pyhd8ed1ab_0
    - pip 24.0 pyhd8ed1ab_0
    - pkginfo 1.9.6 pyhd8ed1ab_0
    - platformdirs 4.2.0 pyhd8ed1ab_0
    - poetry 1.8.0 linux_pyha804496_0
    - poetry-core 1.9.0 pyhd8ed1ab_0
    - poetry-plugin-export 1.6.0 pyhd8ed1ab_0
    - ptyprocess 0.7.0 pyhd3deb0d_0
    - pycparser 2.21 pyhd8ed1ab_0
    - pyproject_hooks 1.0.0 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - python 3.12.2 hab00c5b_0_cpython
    - python-build 1.0.3 pyhd8ed1ab_0
    - python-fastjsonschema 2.19.1 pyhd8ed1ab_0
    - python-installer 0.7.0 pyhd8ed1ab_0
    - python_abi 3.12 4_cp312
    - rapidfuzz 3.6.1 py312h30efb56_0
    - readline 8.2 h8228510_1
    - requests 2.31.0 pyhd8ed1ab_0
    - requests-toolbelt 1.0.0 pyhd8ed1ab_0
    - secretstorage 3.3.3 py312h7900ff3_2
    - setuptools 69.1.1 pyhd8ed1ab_0
    - shellingham 1.5.4 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - tomlkit 0.12.3 pyha770c72_0
    - trove-classifiers 2024.2.23 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - urllib3 2.2.1 pyhd8ed1ab_0
    - virtualenv 20.25.1 pyhd8ed1ab_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - python >=3.6
test:
  commands:
    - pip check
    - archspec --help
  imports:
    - archspec
    - archspec.cpu
  requires:
    - pip
about:
  dev_url: https://github.com/archspec/archspec/
  doc_url: https://archspec.readthedocs.io/
  home: https://pypi.org/project/archspec/
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: A library to query system architecture
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240226.2.1
  recipe-maintainers:
    - anthchirp
    - isuruf
  remote_url: https://github.com/conda-forge/archspec-feedstock
  sha: a38f8a334407350b5cb056abd1528046200c8156
