# This file created by conda-build 3.28.1
# ------------------------------------------------

package:
  name: libarchive
  version: 3.7.2
source:
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - patches/0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
    - patches/0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
    - patches/0006-VC-openssl-define-inline-as-__inline.patch
    - patches/0007-CMake-VC9-compatibility-ignore-some-warnings.patch
  sha256: 63b40acff57467f7d3a64981d4bcff60b52f539fae7688aaaaee27a448b10266
  url: https://github.com/libarchive/libarchive/archive/v3.7.2.tar.gz
build:
  number: 1
  run_exports:
    - libarchive >=3.7.2,<3.8.0a0
  string: h2aa1ff5_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_3
    - gcc_linux-64 12.3.0 h76fc315_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_103
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libnsl 2.0.1 hd590300_0
    - libsanitizer 12.3.0 h0f45ef3_3
    - libstdcxx-ng 13.2.0 h7e041cc_3
    - libtool 2.4.7 h27087fc_0
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 4_hd590300_perl5
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - icu 73.2 h59595ed_0
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libiconv 1.17 h166bdaf_0
    - libstdcxx-ng 13.2.0 h7e041cc_3
    - libxml2 2.12.2 h232c23b_0
    - libzlib 1.2.13 hd590300_5
    - lz4-c 1.9.3 h9c3ff4c_1
    - lzo 2.10 h516909a_1000
    - openssl 3.2.0 hd590300_1
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
    - zstd 1.5.5 hfc55251_0
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libgcc-ng >=12
    - libxml2 >=2.12.2,<2.13.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - lz4-c >=1.9.3,<1.10.0a0
    - lzo >=2.10,<3.0a0
    - openssl >=3.2.0,<4.0a0
    - xz >=5.2.6,<6.0a0
    - zstd >=1.5.5,<1.6.0a0
test:
  commands:
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"
    - test -f "${PREFIX}/include/archive.h"
    - test -f "${PREFIX}/include/archive_entry.h"
    - test -f "${PREFIX}/lib/libarchive.a"
    - test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version
    - bsdtar -tf test/hello_world.xar
  files:
    - test/hello_world.xar
about:
  home: http://www.libarchive.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: Multi-format archive and compression library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20231207.1.1
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
  remote_url: https://github.com/conda-forge/libarchive-feedstock
  sha: c2a74d760c2b32adae32b11c930f1c04c4692925
