# system configuration generated and used by the sysconfig module
build_time_vars = {'ABIFLAGS': '',
 'AR': 'ar',
 'ARFLAGS': 'rc',
 'CC': 'cc -pthread',
 'CCSHARED': '-fPIC',
 'CFLAGS': '-DNDEBUG -O2',
 'CONFINCLUDEPY': '/home/conda/feedstock_root/build_artifacts/pypy3.9_1709882985545/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/pypy3.9',
 'CXX': 'c++ -pthread',
 'EXE': '',
 'EXT_SUFFIX': '.pypy39-pp73-x86_64-linux-gnu.so',
 'HOST_GNU_TYPE': 'x86_64-pc-linux-gnu',
 'INCLUDEPY': '/home/conda/feedstock_root/build_artifacts/pypy3.9_1709882985545/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/pypy3.9',
 'LDFLAGS': '-Wl,-Bsymbolic-functions',
 'LDLIBRARY': 'libpypy3.9-c.so',
 'LDSHARED': 'cc -pthread -shared -Wl,-Bsymbolic-functions',
 'LDVERSION': '3.9',
 'LIBDIR': '/home/conda/feedstock_root/build_artifacts/pypy3.9_1709882985545/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib',
 'MULTIARCH': 'x86_64-linux-gnu',
 'OPT': '-DNDEBUG -O2',
 'Py_DEBUG': 0,
 'Py_ENABLE_SHARED': 0,
 'SHLIB_SUFFIX': '.so',
 'SIZEOF_VOID_P': 8,
 'SO': '.pypy39-pp73-x86_64-linux-gnu.so',
 'SOABI': 'pypy39-pp73',
 'TZPATH': '/home/conda/feedstock_root/build_artifacts/pypy3.9_1709882985545/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/share/zoneinfo:/home/conda/feedstock_root/build_artifacts/pypy3.9_1709882985545/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/zoneinfo:/home/conda/feedstock_root/build_artifacts/pypy3.9_1709882985545/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/share/lib/zoneinfo:/home/conda/feedstock_root/build_artifacts/pypy3.9_1709882985545/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/../etc/zoneinfo:/usr/share/zoneinfo:/usr/lib/zoneinfo:/usr/share/lib/zoneinfo:/etc/zoneinfo',
 'VERSION': '3.9'}
