CI: azure
bzip2: '1'
c_compiler: gcc
c_compiler_version: '12'
cdt_name: cos6
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: quay.io/condaforge/linux-anvil-cos7-x86_64
expat: '2'
extend_keys:
- extend_keys
- ignore_build_only_deps
- ignore_version
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
libffi: '3.4'
lua: '5'
name_suffix: '3.9'
ncurses: '6'
numpy: '1.22'
openssl: '3'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '3.10'
r_base: '3.5'
sqlite: '3'
target_platform: linux-64
tk: '8.6'
xz: '5'
zlib: '1.2'
