# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Mar 10 13:04:31 2024
# ------------------------------------------------

package:
  name: packaging
  version: '24.0'
source:
  sha256: eb82c5e3e56209074766e6885bb04b8c38a0c015d0a30036ebe7ece34c9989e9
  url: https://pypi.io/packages/source/p/packaging/packaging-24.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/packaging_1710075952259/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - brotli-python 1.1.0 py312h30efb56_1
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - certifi 2024.2.2 pyhd8ed1ab_0
    - charset-normalizer 3.3.2 pyhd8ed1ab_0
    - docutils 0.20.1 py312h7900ff3_3
    - flit 3.9.0 pyhd8ed1ab_0
    - flit-core 3.9.0 pyhd8ed1ab_0
    - idna 3.6 pyhd8ed1ab_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.1 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.1 h2797004_0
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - pip 24.0 pyhd8ed1ab_0
    - pysocks 1.7.1 pyha2e5f31_6
    - python 3.12.2 hab00c5b_0_cpython
    - python_abi 3.12 4_cp312
    - readline 8.2 h8228510_1
    - requests 2.31.0 pyhd8ed1ab_0
    - setuptools 69.1.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli-w 1.0.0 pyhd8ed1ab_0
    - tzdata 2024a h0c530f3_0
    - urllib3 2.2.1 pyhd8ed1ab_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
test:
  commands:
    - pip check
  imports:
    - packaging
  requires:
    - pip
about:
  home: https://github.com/pypa/packaging
  license: Apache-2.0
  license_file: LICENSE
  summary: Core utilities for Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240310.3.1
  recipe-maintainers:
    - jakirkham
    - nicoddemus
  remote_url: https://github.com/conda-forge/packaging-feedstock
  sha: 8254020c8425d6e4b7566c6f1fac0a08f547f895
