# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Oct  3 17:54:51 2023
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.6
source:
  sha256: b0014986321e77a36d8fe24827698aae076500c817133a700608bd677b77a998
  url: https://github.com/conda/pycosat/archive/0.6.6.tar.gz
build:
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pycosat_1696355779099/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps -vv
  string: py39hf860d4a_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_2
    - gcc_linux-64 12.3.0 h76fc315_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_2
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libsanitizer 12.3.0 h0f45ef3_2
    - libstdcxx-ng 13.2.0 h7e041cc_2
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - expat 2.5.0 hcb278e6_1
    - gdbm 1.18 h0a1914f_2
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_2
    - libgomp 13.2.0 h807b86a_2
    - libsqlite 3.43.0 h2797004_0
    - libxcb 1.15 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.3 hd590300_0
    - pip 23.2.1 pyhd8ed1ab_0
    - pthread-stubs 0.4 h36c2ea0_1001
    - pypy3.9 7.3.13 h9557127_0
    - python 3.9.18 0_73_pypy
    - python_abi 3.9 4_pypy39_pp73
    - readline 8.2 h8228510_1
    - setuptools 68.2.2 pyhd8ed1ab_0
    - sqlite 3.43.0 h2c6b66d_0
    - tk 8.6.13 h2797004_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xorg-kbproto 1.0.7 h7f98852_1002
    - xorg-libx11 1.8.6 h8ee46fc_0
    - xorg-libxau 1.0.11 hd590300_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-xextproto 7.3.0 h0b41bf4_1003
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
  run:
    - libgcc-ng >=12
    - pypy3.9 >=7.3.13
    - python >=3.9,<3.10.0a0
    - python_abi 3.9 *_pypy39_pp73
test:
  commands:
    - pip check
    - python test_package.py "0.6.6"
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  imports:
    - pycosat
  requires:
    - pip
about:
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  dev_url: https://github.com/conda/pycosat
  doc_source_url: https://github.com/conda/pycosat/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/pycosat
  home: https://github.com/conda/pycosat
  license: MIT
  license_file:
    - COPYRIGHT
    - LICENSE
  summary: Bindings to picosat (a SAT solver)
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - msarahan
    - nehaljwani
    - pelson
