# This file created by conda-build 3.28.4
# ------------------------------------------------

package:
  name: cffi
  version: 1.16.0
build:
  noarch: generic
  number: 1
  string: 1_pypy39
requirements:
  build: []
  run:
    - pypy3.9 7.3.15.*
    - python 3.9.18 1_73_pypy
    - python_abi 3.9 *_pypy39_pp73
test:
  commands:
    - test $(python -c "import cffi;print(cffi.__version__)") == "1.16.0"
about:
  home: https://github.com/conda-forge/pypy-meta-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Metapackage to select pypy as python implementation
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240206.1.1
  recipe-maintainers:
    - isuruf
    - mattip
  remote_url: https://github.com/conda-forge/pypy-meta-feedstock
  sha: 12404366a61053e73e5187e071babdabf03347ce
