# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.28
source:
  fn: libsolv-0.7.28.tar.gz
  patches:
    - conda_variant_priorization.patch
    - no_error_subdir_mismatch.patch
  sha256: bd2406f498fea6086ae0eacbf8b188c98b380e59af2267170e6a7b7d715cb207
  url: https://github.com/openSUSE/libsolv/archive/0.7.28.tar.gz
build:
  number: 2
  run_exports:
    - libsolv >=0.7.28,<0.8.0a0
  string: hfc55251_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hdade7a5_3
    - bzip2 1.0.8 hd590300_5
    - c-ares 1.27.0 hd590300_0
    - ca-certificates 2024.2.2 hbcca054_0
    - cmake 3.29.0 hcfe8598_0
    - gcc_impl_linux-64 12.3.0 he2b93b0_5
    - gcc_linux-64 12.3.0 h6477408_3
    - gxx_impl_linux-64 12.3.0 he2b93b0_5
    - gxx_linux-64 12.3.0 h4a1b8e8_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libcurl 8.7.1 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libexpat 2.6.2 h59595ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnghttp2 1.58.0 h47da74e_1
    - libsanitizer 12.3.0 h0f45ef3_5
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_105
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libuv 1.48.0 hd590300_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - ninja 1.11.1 h924138e_0
    - openssl 3.2.1 hd590300_1
    - rhash 1.4.4 hd590300_0
    - sysroot_linux-64 2.12 he073ed8_17
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.5 hfc55251_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libzlib 1.2.13 hd590300_5
    - zlib 1.2.13 hd590300_5
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f "${PREFIX}/lib/libsolv${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libsolvext${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libsolv.so.1"
    - test -f "${PREFIX}/include/solv/repo.h"
    - dumpsolv -h
    - cmake -G Ninja -S test/ -B build/ -D LIB_NAME="libsolv${SHLIB_EXT}" ${CMAKE_ARGS}
    - cmake --build build/
    - cmake --build build --target test
  files:
    - test/*
  requires:
    - cmake
    - gcc_linux-64 12.*
    - gxx_linux-64 12.*
    - ninja
about:
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240327.2.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - pavelzw
    - wolfv
  remote_url: https://github.com/conda-forge/libsolv-feedstock
  sha: 76eeb8077c40f51a1511a8608e1eb31c97b58381
