# This file created by conda-build 24.1.2
# ------------------------------------------------

package:
  name: openssl
  version: 3.2.1
source:
  sha256: 83c7329fe52c850677d75e5d0b0ca245309b97e8ecbcfdc1dfdc4ab9fac35b39
  url: http://www.openssl.org/source/openssl-3.2.1.tar.gz
build:
  no_link: lib/libcrypto.so.3.0
  number: 1
  run_exports:
    - openssl >=3.2.1,<4.0a0
  string: hd590300_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hdade7a5_3
    - gcc_impl_linux-64 12.3.0 he2b93b0_5
    - gcc_linux-64 12.3.0 h6477408_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libsanitizer 12.3.0 h0f45ef3_5
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libxcrypt 4.4.36 hd590300_1
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 7_hd590300_perl5
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
  run:
    - ca-certificates
    - libgcc-ng >=12
  run_constrained:
    - pyopenssl >=22.1
test:
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
    - pkg-config --print-errors --exact-version "3.2.1" openssl
  requires:
    - pkg-config
about:
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man3.0/
  home: http://www.openssl.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  feedstock-name: openssl
  final: true
  flow_run_id: azure_20240318.2.1
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/openssl-feedstock
  sha: f0405d0216596d5d846847ea3ecd565702634e45
