# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Apr  1 01:52:01 2024
# ------------------------------------------------

package:
  name: boltons
  version: 24.0.0
source:
  fn: boltons-24.0.0.tar.gz
  sha256: f55bb241f15be5761803216ae7509e9270faf8e3e8687e744ab61a401ddd20ff
  url: https://github.com/mahmoud/boltons/archive/24.0.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/boltons_1711936407380/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.45.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - python =2.7|>=3.7
test:
  commands:
    - pytest --doctest-modules boltons tests
  requires:
    - pytest
  source_files:
    - boltons
    - pytest.ini
    - tests
about:
  home: https://github.com/mahmoud/boltons
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'boltons should be builtins. Boltons is a set of over 160 BSD-licensed,
    pure-Python utilities in the same spirit as--and yet conspicuously missing from--the
    standard library.

    '
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240331.2.1
  recipe-maintainers:
    - kalefranz
    - nicoddemus
  remote_url: https://github.com/conda-forge/boltons-feedstock
  sha: 0a2a7cf1423a1e5519ac21ec2eeceb1563722a45
