# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Aug 16 23:50:42 2020
# ------------------------------------------------

package:
    name: gdbm
    version: '1.18'
source:
    patches:
        - gdbm_gcc_10.patch
    sha1: 0f1056ab3beb1bf09dad06f8083f2c79716a5b1b
    url: ftp://ftp.gnu.org/gnu/gdbm/gdbm-1.18.tar.gz
build:
    number: '2'
    run_exports:
        - gdbm >=1.18,<1.19.0a0
    string: h0a1914f_2
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.34 h2122c62_9
        - binutils_linux-64 2.34 h47ac705_27
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_27
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.34 hc38a660_9
        - libgcc-ng 9.3.0 h24d8f2e_15
        - libgomp 9.3.0 h24d8f2e_15
        - libstdcxx-ng 9.3.0 hdf63c60_15
        - libtool 2.4.6 h516909a_1003
        - make 4.3 h516909a_0
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h24d8f2e_15
        - libgomp 9.3.0 h24d8f2e_15
        - libstdcxx-ng 9.3.0 hdf63c60_15
        - ncurses 6.2 he1b5a44_1
        - readline 8.0 he28a2e2_2
    run:
        - libgcc-ng >=7.5.0
        - readline >=8.0,<9.0a0
test:
    commands:
        - gdbm_dump --version
        - gdbm_load --version
        - gdbmtool --version
about:
    home: https://www.gnu.org.ua/software/gdbm/
    license: GPL-3.0
    license_family: GPL
    license_file: COPYING
    summary: 'A library of database functions that use extensible hashing and works
        similar to the standard UNIX dbm functions.

        '
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - hmaarrfk
        - jakirkham
