# This file created by conda-build 3.28.4
# ------------------------------------------------

package:
  name: libgcc-ng
  version: 13.2.0
source:
  - patches:
      - patches/0021-Hardcode-HAVE_ALIGNED_ALLOC-1-in-libstdc-v3-configur.patch
      - patches/libgomp-support-environ-null.patch
      - patches/new-allow-commands-in-main-specfile.patch
    sha256: 8cb4be3796651976f94b9356fa08d833524f62420d6292c5033a9a26af315078
    url: https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.gz
build:
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - __glibc
  missing_dso_whitelist:
    - '*'
  number: 5
  rpaths_patcher: patchelf
  string: h807b86a_5
requirements:
  build:
    - binutils_impl_linux-64 2.39 he00db2b_1
    - gcc_bootstrap_linux-64 13.2.0 h4dbdac4_2
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _openmp_mutex 4.5 2_gnu
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - libgomp 13.2.0 h807b86a_5
    - sysroot_linux-64 2.12 he073ed8_16
  run:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex >=4.5
  run_constrained:
    - libgomp 13.2.0 h807b86a_5
test:
  commands:
    - test -f ${PREFIX}/lib/libgcc_s.so
    - test -f ${PREFIX}/lib/libgomp.so.1
    - test `readlink ${PREFIX}/lib/libgomp.so.1` == "libgomp.so.1.0.0"
  requires:
    - sysroot_linux-64
about:
  home: https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GCC low-level runtime library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - isuruf
    - timsnyder
    - xhochy
