# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jan 31 15:01:49 2024
# ------------------------------------------------

package:
  name: platformdirs
  version: 4.2.0
source:
  sha256: ef0cc731df711022c174543cb70a9b5bd22e5a9337c8624ef2c2ceb8ddad8768
  url: https://pypi.io/packages/source/p/platformdirs/platformdirs-4.2.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/platformdirs_1706713388748/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - editables 0.5 pyhd8ed1ab_0
    - hatch-vcs 0.4.0 pyhd8ed1ab_0
    - hatchling 1.21.1 pyhd8ed1ab_0
    - importlib-metadata 7.0.1 pyha770c72_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_4
    - libgomp 13.2.0 h807b86a_4
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - packaging 23.2 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 23.3.2 pyhd8ed1ab_0
    - pluggy 1.4.0 pyhd8ed1ab_0
    - python 3.12.1 hab00c5b_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.0.3 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2024.1.8 pyhd8ed1ab_0
    - typing-extensions 4.9.0 hd8ed1ab_0
    - typing_extensions 4.9.0 pyha770c72_0
    - tzdata 2023d h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - python >=3.8
test:
  commands:
    - pip check
    - mypy -p platformdirs --ignore-missing-imports
  imports:
    - platformdirs
  requires:
    - mypy
    - pip
about:
  dev_url: https://github.com/platformdirs/platformdirs
  home: https://github.com/platformdirs/platformdirs
  license: MIT
  license_file: LICENSE
  summary: A small Python module for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240131.2.1
  recipe-maintainers:
    - adament
    - bollwyvl
    - gaborbernat
  remote_url: https://github.com/conda-forge/platformdirs-feedstock
  sha: 5341d02f48d9f52d09c6ce5cb22d2d2dcf5fb2b8
