# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Apr 21 13:02:07 2023
# ------------------------------------------------

package:
  name: libxcb
  version: '1.15'
source:
  fn: libxcb-1.15.tar.bz2
  patches: null
  sha256: 1cb65df8543a69ec0555ac696123ee386321dfac1964a3da39976c9a05ad724d
  url: https://xorg.freedesktop.org/archive/individual/lib/libxcb-1.15.tar.gz
build:
  detect_binary_files_with_prefix: true
  number: '0'
  run_exports:
    - libxcb >=1.15,<1.16.0a0
  string: h0b41bf4_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.39 he00db2b_1
    - binutils_linux-64 2.39 h5fc0e48_12
    - gcc_impl_linux-64 11.3.0 hab1b70f_19
    - gcc_linux-64 11.3.0 he6f903b_12
    - gettext 0.21.1 h27087fc_0
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libgcc-devel_linux-64 11.3.0 h210ce93_19
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsanitizer 11.3.0 h239ccf8_19
    - libstdcxx-ng 12.2.0 h46fd767_19
    - libtool 2.4.7 h27087fc_0
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 2_h7f98852_perl5
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_15
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.1.0 h0b41bf4_0
    - pthread-stubs 0.4 h36c2ea0_1001
    - python 3.11.3 h2755cc3_0_cpython
    - python_abi 3.11 3_cp311
    - readline 8.2 h8228510_1
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - xcb-proto 1.15 py311h459d7ec_1
    - xorg-libxau 1.0.9 h7f98852_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-util-macros 1.19.3 h7f98852_0
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
  run:
    - libgcc-ng >=12
    - pthread-stubs
    - xorg-libxau
    - xorg-libxdmcp
test:
  commands:
    - test -f $PREFIX/lib/libxcb.so
    - test -f $PREFIX/lib/libxcb-composite.so
    - test -f $PREFIX/lib/libxcb-damage.so
    - test -f $PREFIX/lib/libxcb-dpms.so
    - test -f $PREFIX/lib/libxcb-dri2.so
    - test -f $PREFIX/lib/libxcb-glx.so
    - test -f $PREFIX/lib/libxcb-present.so
    - test -f $PREFIX/lib/libxcb-randr.so
    - test -f $PREFIX/lib/libxcb-record.so
    - test -f $PREFIX/lib/libxcb-res.so
    - test -f $PREFIX/lib/libxcb-screensaver.so
    - test -f $PREFIX/lib/libxcb-shape.so
    - test -f $PREFIX/lib/libxcb-shm.so
    - test -f $PREFIX/lib/libxcb-sync.so
    - test -f $PREFIX/lib/libxcb-xf86dri.so
    - test -f $PREFIX/lib/libxcb-xfixes.so
    - test -f $PREFIX/lib/libxcb-xinerama.so
    - test -f $PREFIX/lib/libxcb-xkb.so
    - test -f $PREFIX/lib/libxcb-xtest.so
    - test -f $PREFIX/lib/libxcb-xv.so
    - test -f $PREFIX/lib/libxcb-xvmc.so
    - test -f $PREFIX/lib/libxcb-dri3.so
    - test -f $PREFIX/lib/libxcb-render.so
    - test -f $PREFIX/lib/libxcb-xinput.so
about:
  home: http://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is the C-language Binding (XCB) package to the X Window System protocol
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - pkgw
