# This file created by conda-build 24.3.0
# ------------------------------------------------

package:
  name: libmamba
  version: 1.5.8
source:
  sha256: 6ddaf4b0758eb7ca1250f427bc40c2c3ede43257a60bac54e4320a4de66759a6
  url: https://github.com/mamba-org/mamba/archive/refs/tags/2024.03.25.tar.gz
build:
  ignore_run_exports:
    - spdlog
  number: 0
  run_exports:
    - libmamba >=1.5.8,<1.6.0a0
  string: had39da4_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hdade7a5_3
    - bzip2 1.0.8 hd590300_5
    - c-ares 1.27.0 hd590300_0
    - ca-certificates 2024.2.2 hbcca054_0
    - cmake 3.29.0 hcfe8598_0
    - gcc_impl_linux-64 12.3.0 he2b93b0_5
    - gcc_linux-64 12.3.0 h6477408_3
    - gxx_impl_linux-64 12.3.0 he2b93b0_5
    - gxx_linux-64 12.3.0 h4a1b8e8_3
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libcurl 8.6.0 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libexpat 2.6.2 h59595ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libnghttp2 1.58.0 h47da74e_1
    - libsanitizer 12.3.0 h0f45ef3_5
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_105
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libuv 1.48.0 hd590300_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4.20240210 h59595ed_0
    - ninja 1.11.1 h924138e_0
    - openssl 3.2.1 hd590300_1
    - rhash 1.4.4 hd590300_0
    - sysroot_linux-64 2.12 he073ed8_17
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.5 hfc55251_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - c-ares 1.27.0 hd590300_0
    - ca-certificates 2024.2.2 hbcca054_0
    - cli11 2.4.1 h59595ed_0
    - cpp-expected 1.1.0 hf52228f_0
    - fmt 10.2.1 h00ab1b0_0
    - icu 73.2 h59595ed_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - libarchive 3.7.2 h2aa1ff5_1
    - libcurl 8.6.0 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libiconv 1.17 hd590300_2
    - libnghttp2 1.58.0 h47da74e_1
    - libsolv 0.7.28 hfc55251_1
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libxml2 2.12.6 h232c23b_1
    - libzlib 1.2.13 hd590300_5
    - lz4-c 1.9.4 hcb278e6_0
    - lzo 2.10 h516909a_1000
    - ncurses 6.4.20240210 h59595ed_0
    - nlohmann_json 3.11.3 h59595ed_0
    - openssl 3.2.1 hd590300_1
    - reproc 14.2.4.post0 hd590300_1
    - reproc-cpp 14.2.4.post0 h59595ed_1
    - spdlog 1.12.0 hd2e6256_2
    - xz 5.2.6 h166bdaf_0
    - yaml-cpp 0.8.0 h59595ed_0
    - zstd 1.5.5 hfc55251_0
  run:
    - fmt >=10.2.1,<11.0a0
    - libarchive >=3.7.2,<3.8.0a0
    - libcurl >=8.6.0,<9.0a0
    - libgcc-ng >=12
    - libsolv >=0.7.23
    - libstdcxx-ng >=12
    - openssl >=3.2.1,<4.0a0
    - reproc >=14.2,<15.0a0
    - reproc-cpp >=14.2,<15.0a0
    - yaml-cpp >=0.8.0,<0.9.0a0
    - zstd >=1.5.5,<1.6.0a0
test:
  commands:
    - test -d ${PREFIX}/include/mamba
    - test -f ${PREFIX}/include/mamba/version.hpp
    - test -f ${PREFIX}/lib/cmake/libmamba/libmambaConfig.cmake
    - test -f ${PREFIX}/lib/cmake/libmamba/libmambaConfigVersion.cmake
    - test -e ${PREFIX}/lib/libmamba${SHLIB_EXT}
    - cat $PREFIX/include/mamba/version.hpp | grep "LIBMAMBA_VERSION_MAJOR 1"
    - cat $PREFIX/include/mamba/version.hpp | grep "LIBMAMBA_VERSION_MINOR 5"
    - cat $PREFIX/include/mamba/version.hpp | grep "LIBMAMBA_VERSION_PATCH 8"
about:
  description: '

    [![Build Status](https://github.com/mamba-org/mamba/workflows/CI/badge.svg)](https://github.com/mamba-org/mamba/actions)

    [![Join the Gitter Chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/mamba-org/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

    [![docs](https://readthedocs.org/projects/mamba/badge/?version=latest&style=flat)](https://mamba.readthedocs.io/en/latest)


    `mamba` is a reimplementation of the conda package manager in C++.


    - parallel downloading of repository data and package files using multi-threading

    - libsolv for much faster dependency solving, a state of the art library used
    in the RPM package manager of Red Hat, Fedora and OpenSUSE

    - core parts of `mamba` are implemented in C++ for maximum efficiency


    At the same time, `mamba` utilizes the same command line parser, package installation
    and deinstallation code and transaction verification routines as `conda` to stay
    as compatible as possible.


    Mamba is part of a bigger ecosystem to make scientific packaging more sustainable.
    You can read our [announcement blog post](https://medium.com/@QuantStack/open-software-packaging-for-science-61cecee7fc23).

    The ecosystem also consists of `quetz`, an open source `conda` package server
    and `boa`, a fast `conda` package builder.



    Please refer to the [`mamba` and `micromamba` installation guide](https://mamba.readthedocs.io/en/latest/installation.html)
    in the documentation.



    `mamba` and `micromamba` come with features on top of stock `conda`.



    To efficiently query repositories and query package dependencies you can use `mamba
    repoquery` or `micromamba repoquery`.

    See the [repoquery documentation](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html#repoquery)
    for details.



    `micromamba` can be used to install lock files generated by [conda-lock](https://conda-incubator.github.io/conda-lock/)
    without having to install `conda-lock`. Simply invoke e.g. `micromamba create
    -n my-env -f conda-lock.yml` with an environment lockfile named `*-lock.yml` or
    `*-lock.yaml`.

    '
  dev_url: https://github.com/mamba-org/mamba
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A fast drop-in alternative to conda, using libsolv for dependency resolution
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240325.4.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - ericmjl
    - wolfv
  remote_url: https://github.com/conda-forge/mamba-feedstock
  sha: a3c12339b32b1d3efc19ac41db26f6bac7c96ef5
