# This file created by conda-build 3.28.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jan 12 14:03:47 2024
# ------------------------------------------------

package:
  name: menuinst
  version: 2.0.2
source:
  sha256: 2846d3435b13375fe9242a985f355c176ace7a31072c230bdd5b0bfd13367701
  url: https://github.com/conda/menuinst/archive/2.0.2.tar.gz
build:
  number: '0'
  script:
    - rm -f "/home/conda/feedstock_root/build_artifacts/menuinst_1705068298693/work/menuinst/data/osx_launcher_*"
    - rm -f "/home/conda/feedstock_root/build_artifacts/menuinst_1705068298693/work/menuinst/data/appkit_launcher_*"
    - /home/conda/feedstock_root/build_artifacts/menuinst_1705068298693/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
      -m pip install . -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=2.0.2
  string: py39h4162558_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - expat 2.5.0 hcb278e6_1
    - gdbm 1.18 h0a1914f_2
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libsqlite 3.44.2 h2797004_0
    - libxcb 1.15 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.0 hd590300_1
    - packaging 23.2 pyhd8ed1ab_0
    - pip 23.3.2 pyhd8ed1ab_0
    - pthread-stubs 0.4 h36c2ea0_1001
    - pypy3.9 7.3.13 h9557127_1
    - python 3.9.18 0_73_pypy
    - python_abi 3.9 4_pypy39_pp73
    - readline 8.2 h8228510_1
    - setuptools 69.0.3 pyhd8ed1ab_0
    - setuptools-scm 8.0.4 pyhd8ed1ab_0
    - setuptools_scm 8.0.4 hd8ed1ab_0
    - sqlite 3.44.2 h2c6b66d_0
    - tk 8.6.13 noxft_h4845f30_101
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.9.0 hd8ed1ab_0
    - typing_extensions 4.9.0 pyha770c72_0
    - tzdata 2023d h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xorg-kbproto 1.0.7 h7f98852_1002
    - xorg-libx11 1.8.7 h8ee46fc_0
    - xorg-libxau 1.0.11 hd590300_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-xextproto 7.3.0 h0b41bf4_1003
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
  run:
    - pypy3.9 >=7.3.13
    - python >=3.9,<3.10.0a0
    - python_abi 3.9 *_pypy39_pp73
test:
  commands: null
  imports:
    - menuinst
    - menuinst.api
about:
  doc_url: https://conda.github.io/menuinst/
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240112.2.1
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
  remote_url: https://github.com/conda-forge/menuinst-feedstock
  sha: 100bc037d6759541cb8e55194037ae1239f0c90b
