# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.5
source:
  patches: null
  sha256: 98e9c3d949d1b924e28e01eccb7deed865eefebf25c2f21c702e5cd5b63b85e1
  url: https://github.com/facebook/zstd/archive/v1.5.5.tar.gz
build:
  number: 0
  run_exports:
    - zstd >=1.5.5,<1.6.0a0
  string: hfc55251_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_1
    - cmake-no-system 3.27.4 h59595ed_0
    - gcc_impl_linux-64 12.3.0 he2b93b0_0
    - gcc_linux-64 12.3.0 h76fc315_1
    - gxx_impl_linux-64 12.3.0 he2b93b0_0
    - gxx_linux-64 12.3.0 h8a814eb_1
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_0
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libsanitizer 12.3.0 h0f45ef3_0
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_0
    - libstdcxx-ng 13.1.0 hfd8a6a1_0
    - make 4.3 hd18ef5c_1
    - ninja 1.11.1 h924138e_0
    - sysroot_linux-64 2.12 he073ed8_16
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libstdcxx-ng 13.1.0 hfd8a6a1_0
    - libzlib 1.2.13 hd590300_5
    - zlib 1.2.13 hd590300_5
  run:
    - libgcc-ng >=12
    - libstdcxx-ng >=12
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libzstd.so
    - test ! -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/include/zstd.h
    - zstd -be -i5
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - pkg-config --cflags libzstd
    - cd cf_test
    - cmake $CMAKE_ARGS .
  files:
    - cf_test/
  requires:
    - cmake
    - gcc_linux-64 12.*
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: http://www.zstd.net
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  feedstock-name: zstd
  final: true
  recipe-maintainers:
    - hmaarrfk
    - msarahan
    - rmax
    - xhochy
