# This file created by conda-build 3.28.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jan  3 22:36:25 2024
# ------------------------------------------------

package:
  name: distro
  version: 1.9.0
source:
  fn: distro-1.9.0.tar.gz
  sha256: 2fa77c6fd8940f116ee1d6b94a2f90b13b5ea8d019b98bc8bafdcabcdd9bdbed
  url: https://pypi.io/packages/source/d/distro/distro-1.9.0.tar.gz
build:
  entry_points:
    - distro = distro.distro:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/distro_1704321475663/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2023.11.17 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h807b86a_3
    - libgomp 13.2.0 h807b86a_3
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.44.2 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.0 hd590300_1
    - pip 23.3.2 pyhd8ed1ab_0
    - python 3.12.1 hab00c5b_1_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.0.3 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2023d h0c530f3_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.6
test:
  commands:
    - pip check
    - distro --help
    - pytest -vvv --capture=tee-sys tests
  imports:
    - distro
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  dev_url: https://github.com/nir0s/distro
  doc_url: http://distro.readthedocs.io/en/latest/
  home: https://github.com/nir0s/distro
  license: Apache-2.0
  license_file: LICENSE
  summary: Provides information about the OS distribution it runs on, such as a reliable
    machine-readable ID, or version information.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240103.2.1
  recipe-maintainers:
    - abloemert
    - thewchan
  remote_url: https://github.com/conda-forge/distro-feedstock
  sha: 87a0ad811236289d80cb1d767816a027816dbcc8
