# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Aug 17 16:29:06 2020
# ------------------------------------------------

package:
    name: lzo
    version: '2.10'
source:
    sha256: c0f892943208266f9b6543b3ae308fab6284c5c90e627931446fb49b4221a072
    url: http://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz
build:
    number: '1000'
    run_exports:
        - lzo >=2.10,<3.0a0
    string: h516909a_1000
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.34 h2122c62_9
        - binutils_linux-64 2.34 h47ac705_27
        - bzip2 1.0.8 h516909a_2
        - c-ares 1.16.1 h516909a_0
        - ca-certificates 2020.6.20 hecda079_0
        - cmake 3.18.0 h5c55442_0
        - expat 2.2.9 he1b5a44_2
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_27
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - krb5 1.17.1 hfafb76e_2
        - ld_impl_linux-64 2.34 hc38a660_9
        - libcurl 7.71.1 hcdd3856_4
        - libedit 3.1.20191231 he28a2e2_2
        - libev 4.33 h516909a_0
        - libgcc-ng 9.3.0 h24d8f2e_15
        - libgomp 9.3.0 h24d8f2e_15
        - libnghttp2 1.41.0 hab1572f_1
        - libssh2 1.9.0 hab1572f_5
        - libstdcxx-ng 9.3.0 hdf63c60_15
        - libuv 1.38.0 h516909a_0
        - make 4.3 h516909a_0
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - rhash 1.3.6 h14c3975_1001
        - sysroot_linux-64 2.12 h77966d4_13
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1007
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h24d8f2e_15
        - libgomp 9.3.0 h24d8f2e_15
    run:
        - libgcc-ng >=7.5.0
test:
    commands:
        - test -f ${PREFIX}/include/lzo/lzoconf.h
        - test -f ${PREFIX}/lib/liblzo2.a
        - test -f ${PREFIX}/lib/liblzo2${SHLIB_EXT}
about:
    description: 'LZO offers pretty fast compression and extremely fast decompression.

        MiniLZO is a very lightweight subset of the LZO library.

        '
    home: http://www.oberhumer.com/opensource/lzo/
    license: GPL v2+
    license_family: GPL2
    license_file: COPYING
    summary: LZO is a portable lossless data compression library written in ANSI C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - rmax
