# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug  3 07:33:40 2023
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 2.2.0
source:
  sha256: dae0c697cf8757d997d0d7f4fbe48a5516cb17f16b3715dadb6008ade8ef850e
  url: https://github.com/conda/conda-package-handling/archive/2.2.0.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/conda-package-handling_1691048088238/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps -vv
  string: pyh38be061_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2023.7.22 hbcca054_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.5.0 hcb278e6_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.42.0 h2797004_0
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - openssl 3.1.2 hd590300_0
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.11.4 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 68.0.0 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.0 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - conda-package-streaming >=0.9.0
    - python >=3.7
    - zstandard >=0.15
test:
  commands:
    - pytest -v --cov=conda_package_handling --color=yes tests/
  imports:
    - conda_package_handling
    - conda_package_handling.api
  requires:
    - mock
    - pytest
    - pytest-cov
    - pytest-mock
  source_files:
    - tests
about:
  dev_url: https://github.com/conda/conda-package-handling
  doc_url: https://conda.github.io/conda-package-handling/
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: Create and extract conda packages of various formats
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - dbast
    - dholth
    - jezdez
    - msarahan
